apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hpa-video.fullname" . }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}  
  selector:
    matchLabels:
      run: {{ .Values.name }}
  template:
    metadata:
      labels:
        run: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
          - containerPort: 80
          resources: # this is new! defining resource limits and requests
            {{- toYaml .Values.resources | nindent 12 }} # brings in the yaml defined in values.yaml and indents it appropriately
