apiVersion: v1
kind: Service
metadata:
  name: {{ include "hpa-video.fullname" . }}
  labels:
    run: {{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    run: {{ .Values.name }}